@echo off
setlocal enabledelayedexpansion

:: ============================================================================
:: Android SDK/NDK Setup Script
:: Tries multiple download sources (Google CN, Tencent, Google direct).
:: If all fail, provides manual download instructions.
:: ============================================================================

set "SDK_ROOT=%~dp0..\android\sdk"
set "CMDLINE_TOOLS_ZIP=%TEMP%\android-cmdline-tools.zip"
set "LOCAL_PROPS=%~dp0..\android\local.properties"

echo ============================================
echo  Android SDK/NDK Setup
echo ============================================

:: ── Check if user already has Android Studio SDK installed ──────────────────
:: Common locations
for %%D in (
    "%LOCALAPPDATA%\Android\Sdk"
    "%USERPROFILE%\AppData\Local\Android\Sdk"
    "C:\Android\sdk"
) do (
    if exist "%%~D\platform-tools\adb.exe" (
        echo [OK] Found existing Android SDK at: %%~D
        set "SDK_ROOT=%%~D"
        goto :write_local_properties
    )
)

:: Check Java
where java >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Java not found on PATH. Please install JDK 17+ first.
    exit /b 1
)
echo [OK] Java found.

:: Check if our local SDK already installed
if exist "%SDK_ROOT%\platform-tools\adb.exe" (
    echo [OK] Android SDK already installed at %SDK_ROOT%
    goto :write_local_properties
)

:: Create SDK directory
if not exist "%SDK_ROOT%" mkdir "%SDK_ROOT%"

:: ── Download command-line tools (try multiple sources) ──────────────────────
echo.
echo [1/4] Downloading Android command-line tools...
if exist "%SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat" goto :sdk_tools_ready

:: Try source 1: Google direct
echo   Trying dl.google.com ...
curl -L --connect-timeout 15 -o "%CMDLINE_TOOLS_ZIP%" "https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip" >nul 2>&1
if not errorlevel 1 if exist "%CMDLINE_TOOLS_ZIP%" goto :extract_tools

:: Try source 2: Google China mirror
echo   Trying dl.google.cn ...
curl -L --connect-timeout 15 -o "%CMDLINE_TOOLS_ZIP%" "https://dl.google.cn/android/repository/commandlinetools-win-11076708_latest.zip" >nul 2>&1
if not errorlevel 1 if exist "%CMDLINE_TOOLS_ZIP%" goto :extract_tools

:: All downloads failed — give manual instructions
echo.
echo =====================================================================
echo  [!] Cannot download Android SDK automatically (network restricted).
echo.
echo  Please install manually:
echo.
echo  Option A: Install Android Studio
echo    Download from: https://developer.android.google.cn/studio
echo    It includes SDK, NDK, and all build tools.
echo    After install, run this script again — it will detect the SDK.
echo.
echo  Option B: Download command-line tools manually
echo    1. Download the ZIP from your browser:
echo       https://developer.android.google.cn/studio#command-line-tools-only
echo    2. Extract to: %SDK_ROOT%\cmdline-tools\latest\
echo    3. Run this script again.
echo =====================================================================
exit /b 1

:extract_tools
echo [1/4] Extracting...
powershell -Command "Expand-Archive -Force '%CMDLINE_TOOLS_ZIP%' '%SDK_ROOT%\cmdline-tools-tmp'"
if not exist "%SDK_ROOT%\cmdline-tools" mkdir "%SDK_ROOT%\cmdline-tools"
if exist "%SDK_ROOT%\cmdline-tools\latest" rmdir /s /q "%SDK_ROOT%\cmdline-tools\latest"
move "%SDK_ROOT%\cmdline-tools-tmp\cmdline-tools" "%SDK_ROOT%\cmdline-tools\latest" >nul
rmdir /s /q "%SDK_ROOT%\cmdline-tools-tmp" 2>nul
del "%CMDLINE_TOOLS_ZIP%" 2>nul
echo [OK] Command-line tools installed.

:sdk_tools_ready
set "SDKMANAGER=%SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat"

:: Accept licenses
echo.
echo [2/4] Accepting licenses...
echo y| call "%SDKMANAGER%" --sdk_root="%SDK_ROOT%" --licenses >nul 2>&1

:: Install SDK components
echo.
echo [3/4] Installing SDK components (this may take several minutes)...
call "%SDKMANAGER%" --sdk_root="%SDK_ROOT%" ^
    "platform-tools" ^
    "platforms;android-34" ^
    "build-tools;34.0.0" ^
    "ndk;27.0.12077973"

if errorlevel 1 (
    echo [ERROR] Failed to install SDK components.
    echo         If download fails, try using a VPN or install Android Studio manually.
    exit /b 1
)

echo [OK] SDK components installed.

:: Verify
echo.
echo [4/4] Verifying installation...
if exist "%SDK_ROOT%\ndk\27.0.12077973\ndk-build.cmd" (
    echo [OK] NDK 27.0.12077973 verified.
) else (
    echo [WARNING] NDK not found at expected path.
)

:write_local_properties
:: Write local.properties for Gradle
echo.
echo Writing local.properties...
if not exist "%~dp0..\android" mkdir "%~dp0..\android"

:: Convert backslashes to forward slashes for Gradle
set "SDK_FWD=%SDK_ROOT:\=/%"
(
    echo # Auto-generated by setup_android_sdk.bat
    echo sdk.dir=%SDK_FWD%
) > "%LOCAL_PROPS%"
echo [OK] Written: %LOCAL_PROPS%

echo.
echo ============================================
echo  Setup complete!
echo  SDK location: %SDK_ROOT%
echo ============================================
endlocal
